elk:
  extends:
    file: elk.yml
    service: elk
  links:
  - consul:consul

influxdb:
  image: qnib/influxdb
  environment:
  - DC_NAME=dc1
  - FORWARD_TO_LOGSTASH=true
  - CNT_TYPE=service
  ports:
   - "8083:8083"
   - "8086:8086"
   - "2003:2003"
  dns: 127.0.0.1
  hostname: influxdb
  links:
  - consul:consul
  volumes:
   - /opt/influxdb/shared
  privileged: true

kopf:
  image: lmenezes/elasticsearch-kopf
  ports:
  - 8088:80
  links:
  - elk:elk
  environment:
  - KOPF_SERVER_NAME=dockerhost
  - KOPF_ES_SERVERS=172.17.42.1:9200

consul:
  image: qnib/consul
  environment:
  - DC_NAME=dc1
  ports:
   - "8500:8500"
  dns: 127.0.0.1
  hostname: consul
  #privileged: true
